literal
  = literal_bool
  / literal_number
  / literal_string
  / literal_atom

literal_bool
  = "true"
  / "false"

literal_number
  = "0b" "_"* [01] [_01]*
  / "0o" "_"* [0-7] ["_" 0-7]*
  / [0-9][_0-9]*
  / "0x" "_"* [0-9a-fA-F][_0-9a-fA-F]*
  / (([0-9]+ "."? [0-9]*) / ("." [0-9]+)) (([eE][+-]?)? [0-9]+)?

literal_string
  = "\"" ([^"] / "\\\"")* "\""

literal_atom
  = "@" ( ("'" ([^'] / "\\'")+ "'") / ([_a-zA-Z][_a-zA-Z0-9]*))
